name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra
      
    - name: Build
      run: make

    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: mohamedlegheraba_fr
        path: build/mohamedlegheraba_fr.pdf
